embed_assets: on

javascripts:
  libs:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/libs/json2.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/libs/fancybox/*.js
    - public/javascripts/libs/jquery.masonry.min.js
  app:
    - public/javascripts/application.js
    - public/javascripts/controllers.js
    - app/views/**/*.jst
    - public/javascripts/models/*.js
    - public/javascripts/views/*.js
